spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  # true 설정 시 JPA 쿼리문 확인 가능
#  jpa:
#    show-sql: true
#    generate-ddl: true # 추가
#
#    # DDL 정의시 DB의 고유 기능을 사용 가능
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL8Dialect # 추가
#      ddl-auto: create

#    # JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여줌
#    properties:
#      hibernate:
#        format_sql: true
